#! /bin/bash

#
# Generates exposure map for the specified year/month.
#
# Assumes the previous month's exposure map already exists and creates
# the new cumulative exposure map, updates the PNG and HTML
# directories.
#

outdir=./outdir

set -e
set -o pipefail

[ $# -eq 2 ] || {
    echo 'Usage: $0 year month' 1>&2
    exit 1
}

year="$1"
month="$2"

[ -f "$outdir"/cumulative/hrci0c_${year}-$(printf %02d $month).fits.gz ] && {
    echo "'${outdir}/cumulative/hrci0c_${year}-$(printf %02d $month).fits.gz' already exists" 1>&2
    exit 1
}

lyear=$year
(( lmonth=month-1 ))
[ $lmonth -lt 1 ] && {
    lmonth=12
    (( lyear-- ))
}

[ -f "$outdir"/cumulative/hrci0c_${lyear}-$(printf %02d $lmonth).fits.gz ] || {
    echo "'${outdir}/cumulative/hrci0c_${lyear}-$(printf %02d $lmonth).fits.gz' doesn't exist" 1>&2
    exit 1
}

. ~/python3_venv/bin/activate

echo python3 ./src/expmaps_monthly.py \
	$year $month \
	./outdir/monthly

echo /bin/bash ./00_READMEs/02_README_stats

echo python3 ./src/expmaps_cumulative.py \
	-y $year -m $month \
	./outdir/monthly \
	./outdir/cumulative

echo /bin/bash ./00_READMEs/04_README_png

echo /bin/bash ./00_READMEs/05_README_html



