#! /bin/bash

set -e
set -o pipefail

#
# Generates exposure map for the specified year/month.
#
# Assumes the previous month's exposure map already exists and creates
# the new cumulative exposure map, updates the PNG and HTML
# directories.
#

basedir=./outdir
false && {
    rm -rf test
    mkdir -p test/cumulative
    cp -a outdir/{stats,png,monthly} ./test
    cp -a ./outdir/cumulative/*2024-03* ./test/cumulative
}

[ $# -eq 2 -o $# -eq 0 ] || {
    echo "Usage: $0 [year month]" 1>&2
    exit 1
}

if [ $# -eq 0 ]
then
    read year month <<<$(date +'%Y %m')
    month=$(expr $month - 1) # side effect of removing leading zero
    if [ $month -eq 0 ]
    then
	(( year-- ))
	month=12
    fi
else
    year="$1"
    month="$2"
fi

echo Processing $year $month...

[ -f "$basedir"/cumulative/hrci0c_${year}-$(printf %02d $month).fits.gz ] && {
    echo "'$basedir/cumulative/hrci0c_${year}-$(printf %02d $month).fits.gz' already exists" 1>&2
    exit 1
}

lmonth=$month
lyear=$year
[ $lmonth -eq 1 ] && {
    (( lyear-- ))
    lmonth=12
} || {
    (( lmonth-- ))
}

[ -f "$basedir"/cumulative/hrci0c_${lyear}-$(printf %02d $lmonth).fits.gz ] || {
    echo "'$basedir/cumulative/hrci0c_${lyear}-$(printf %02d $lmonth).fits.gz' doesn't exist" 1>&2
    exit 1
}

. ~/python3_venv/bin/activate

python3 ./src/expmaps_monthly.py $year $month "$basedir"/monthly

det=i; subdet=0
python3 ./src/mk_stats.py \
	-c "$basedir"/cumulative \
	"$basedir"/monthly \
	"$basedir"/stats \
	$det $subdet
det=s
for subdet in {0..2}
do
     python3 ./src/mk_stats.py \
	    -c "$basedir"/cumulative \
	    "$basedir"/monthly \
	    "$basedir"/stats \
	    $det $subdet
done

python3 ./src/expmaps_cumulative.py \
	-y $year -m $month \
	"$basedir"/monthly \
	"$basedir"/cumulative

str="Generate PNG files and copy to $basedir (e.g., run the following
commands on remote machine)

rsync -avnz --delete localhost:$(pwd)/$basedir/{monthly,cumulative} $basedir
/bin/bash ./00_READMEs/04_README_png $basedir
rsync -avnz --delete $basedir/png localhost:$(pwd)/$basedir

Press ENTER to continue...
"

echo -n "$str"
read

/bin/bash ./00_READMEs/05_README_html "$basedir"
