#! /bin/bash

#
# Generates dosage map for the specified year/month.
#
# Assumes the previous month's dosage map already exists and creates
# the new cumulative dosage map, updates the PNG and HTML
# directories.
#

set -eo pipefail

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

basedir=/data/hrc/DoseMaps

[ $# -eq 2 -o $# -eq 0 ] || {
    echo "Usage: $0 [year month]" 1>&2
    exit 1
}

# if no arguments given, use the previous month
if [ $# -eq 0 ]
then
    read year month <<<$(date +'%Y %m')
    month=$((10#$month))
    echo $year $month
    ((month--))
    if [ $month -eq 0 ]
    then
	(( year-- ))
	month=12
    fi
else
    year="$1"
    month="$2"
fi

datestr=$(printf %4d-%02d $year $month)

# to test recreating already-completed maps
false && {
    rm -f "$basedir"/{monthly,cumulative}/*${datestr}*
    #cp -a /data/hrc/DoseMaps/stats/* /data/hrc/bak
    for f in "$basedir"/stats/*
    do
	head -n -1 $f > $f.tmp
	mv $f.tmp $f
    done
}

echo Processing ${datestr}... >&2

# Ensure requested year/month cumulative map doesn't already exist
[ -f "$basedir"/cumulative/hrci0c_${datestr}.fits.gz ] && {
    echo "'$basedir/cumulative/hrci0c_${datestr}.fits.gz' already exists" >&2
    exit 1
}

# Ensure cumulative map prior to requested year/month does exist
lmonth=$(( month-1 ))
lyear=$year
[ $lmonth -eq 0 ] && { lmonth=12; (( lyear-- )); }

ldatestr=$(printf %4d-%02d $lyear $lmonth)
[ -f "$basedir"/cumulative/hrci0c_${ldatestr}.fits.gz ] || {
    echo "'$basedir/cumulative/hrci0c_${ldatestr}.fits.gz' doesn't exist" >&2
    exit 1
}

. ~/python3_venv/bin/activate

echo "Generating monthly maps for $datestr" >&2
python3 "$SCRIPTDIR"/../src/dosemaps_monthly.py $year $month "$basedir"/monthly

echo "Calculating statistics for HRC-I maps" 1>&2
det=i; subdet=0
python3 "$SCRIPTDIR"/../src/mk_stats.py \
	-c "$basedir"/cumulative \
	"$basedir"/monthly \
	"$basedir"/stats \
	$det $subdet
det=s
for subdet in {0..2}
do
    detstr=HRC-S$((subdet+1))
    echo "Calculating statistics for $detstr maps" >&2
    python3 "$SCRIPTDIR"/../src/mk_stats.py \
	    -c "$basedir"/cumulative \
	    "$basedir"/monthly \
	    "$basedir"/stats \
	    $det $subdet
done

echo "Generating cumulative maps for $datestr" >&2
python3 "$SCRIPTDIR"/../src/dosemaps_cumulative.py \
	-y $year -m $month \
	"$basedir"/monthly \
	"$basedir"/cumulative

# must be run on a machine with Xvfb
echo "Generating PNG images" >&2
/data/legs/rpete/flight/hrc_dosage_map/00_READMEs/04_README_png

pngdir="$basedir"/png

echo "Generating HTML" >&2
/bin/bash "$SCRIPTDIR"/05_README_html "$basedir"

echo "Updating links in /data/hrc/[is]/DoseMaps" >&2
/bin/bash "$SCRIPTDIR"/06_README_data_hrc_links
