#! /bin/bash

set -e
set -o pipefail

#
# Generates exposure map for the specified year/month.
#
# Assumes the previous month's exposure map already exists and creates
# the new cumulative exposure map, updates the PNG and HTML
# directories.
#

basedir=./outdir
false && {
    rm -rf test
    mkdir -p test/cumulative
    cp -a outdir/{stats,png,monthly} ./test
    cp -a ./outdir/cumulative/*2024-03* ./test/cumulative
}

[ $# -eq 2 -o $# -eq 0 ] || {
    echo "Usage: $0 [year month]" 1>&2
    exit 1
}

# if no arguments given, use the previous month
if [ $# -eq 0 ]
then
    read year month <<<$(date +'%Y %m')
    month=$((10#$month))
    echo $year $month
    ((month--))
    if [ $month -eq 0 ]
    then
	(( year-- ))
	month=12
    fi
else
    year="$1"
    month="$2"
fi

echo Processing $year $month... 1>&2

# Ensure requested year/month cumulative map doesn't already exist
[ -f "$basedir"/cumulative/hrci0c_${year}-$(printf %02d $month).fits.gz ] && {
    echo "'$basedir/cumulative/hrci0c_${year}-$(printf %02d $month).fits.gz' already exists" 1>&2
    exit 1
}

# Ensure cumulative map prior to requested year/month does exist
lmonth=$(( month-1 ))
lyear=$year
[ $lmonth -eq 0 ] && { lmonth=12; (( lyear-- )); }

[ -f "$basedir"/cumulative/hrci0c_${lyear}-$(printf %02d $lmonth).fits.gz ] || {
    echo "'$basedir/cumulative/hrci0c_${lyear}-$(printf %02d $lmonth).fits.gz' doesn't exist" 1>&2
    exit 1
}

datestr=$(printf %4d-%02d $year $month)

. ~/python3_venv/bin/activate

echo "Generating monthly maps for $datestr" 1>&2
python3 ./src/expmaps_monthly.py $year $month "$basedir"/monthly

echo "Calculating statistics for HRC-I maps" 1>&2
det=i; subdet=0
python3 ./src/mk_stats.py \
	-c "$basedir"/cumulative \
	"$basedir"/monthly \
	"$basedir"/stats \
	$det $subdet
det=s
for subdet in {0..2}
do
    detstr=HRC-S$((subdet+1))
    echo "Calculating statistics for $detstr maps" 1>&2
    python3 ./src/mk_stats.py \
	    -c "$basedir"/cumulative \
	    "$basedir"/monthly \
	    "$basedir"/stats \
	    $det $subdet
done

echo "Generating cumulative maps for $datestr" 1>&2
python3 ./src/expmaps_cumulative.py \
	-y $year -m $month \
	"$basedir"/monthly \
	"$basedir"/cumulative

echo "
Next, generate PNG files and copy them to $basedir (e.g., run the
following commands on remote machine)

rsync -avn --delete localhost:$(pwd)/$basedir/{monthly,cumulative} $basedir
/bin/bash ./00_READMEs/04_README_png $basedir
rsync -avn --delete $basedir/png localhost:$(pwd)/$basedir
" 1>&2

echo "Generating HTML" 1>&2
/bin/bash ./00_READMEs/05_README_html "$basedir"
