#! /bin/bash

basedir=`pwd`
wwwdir=/data/wdocs/rpete/HRC_Exposure
outdir=$basedir/outdir

rm -rf $outdir $wwwdir Exc

mkdir -p Exc
mkdir -p $wwwdir/Sub_html
mkdir -p $wwwdir/{Image,Plots}/HRC{I,S}/{Cumulative,Month}
mkdir -p $outdir/{i,s}/Exposure_map/{Data,Image}/{Cumulative,Month}
mkdir -p $outdir/{i,s}/Exposure_map/Stats


export SKA=/proj/sot/ska
export PYTHONPATH=/data/mta/Script/Python3.8/envs/ska3-shiny/lib/python3.8/site-packages:/data/mta/Script/Python3.8/lib/python3.8/site-packages/

cd Exc
../Scripts/hrc_dose_create_run.py 2000 04
