#! /bin/bash

. ~/python3_venv/bin/activate

outdir=./test/expmaps_monthly

for m in {8..12}
do
    python3 ./src/expmaps_monthly.py -o $outdir 1999 $m
done

for y in {2000..2023}
do
    for m in {1..12}
    do
	python3 ./src/expmaps_monthly.py -o $outdir $y $m
    done
done
    


