#! /bin/bash

false && {
  echo 'This script recreates the statistics files.' 1>&2
  exit
}

set -eo pipefail

[ $# -lt 2 ] || {
    echo "Usage: $0 [basedir]" 1>&2
    exit 1
}

basedir=./outdir
[ $# -eq 1 ] && basedir="$1"

indir="$basedir"/monthly
cdir="$basedir"/cumulative
outdir="$basedir"/stats

. ~/python3_venv/bin/activate

screen -dmS stats bash -c 'exec bash'

det=i
subdet=0
screen -S stats -X screen bash -c "time python3 src/mk_stats.py -c $cdir $indir $outdir $det $subdet; exec bash"

det=s
for subdet in {0..2}
do
  screen -S stats -X screen bash -c "time python3 src/mk_stats.py -c $cdir $indir $outdir $det $subdet; exec bash"
done

screen -rS stats
