#! /bin/bash

false && {
  echo 'This script recreates the statistics files.' 1>&2
  exit
}

set -e
set -o pipefail

[ $# -lt 2 ] || {
    echo "Usage: $0 [basedir]" 1>&2
    exit 1
}

basedir=./outdir
[ $# -eq 1 ] && basedir="$1"

indir="$basedir"/monthly
outdir="$basedir"/stats

. ~/python3_venv/bin/activate

screen -dmS stats bash -c 'exec bash'
det=i
for subdet in {0..0}
do
  screen -S stats -X screen bash -c "time python3 src/mk_stats.py $indir $outdir $det $subdet; exec bash"
done
det=s
for subdet in {0..2}
do
  screen -S stats -X screen bash -c "time python3 src/mk_stats.py $indir $outdir $det $subdet; exec bash"
done
screen -rS stats
