#! /bin/bash

. ~/.bash_aliases
shopt -s expand_aliases

# needed for mta_convert_fits_to_img
ciao

. ~/python3_venv/bin/activate

false && {
  basedir=`pwd`
  wwwdir=/data/wdocs/rpete/HRC_Exposure
  outdir=$basedir/outdir

  rm -rf $outdir $wwwdir Exc

  mkdir -p Exc
  mkdir -p $wwwdir/Sub_html
  mkdir -p $wwwdir/{Image,Plots}/HRC{I,S}/{Cumulative,Month}
  mkdir -p $outdir/{i,s}/Exposure_map/{Data,Image}/{Cumulative,Month}
  mkdir -p $outdir/{i,s}/Exposure_map/Stats
}

cd Exc
python3 ../Scripts/hrc_dose_create_run.py 1999 8
#python3 ../Scripts/hrc_dose_create_run.py 1999 9
