#! /bin/bash

. ~/python3_venv/bin/activate

outdir=./test/monthly

for m in {8..12}
do
    time python3 ./src/expmaps_monthly.py 1999 $m $outdir
done

for y in {2000..2023}
do
    for m in {1..12}
    do
	time python3 ./src/expmaps_monthly.py $y $m $outdir
    done
done
