#! /bin/bash

false && {
  echo 'This script recreates the PNG files.' 1>&2
  exit
}

set -eo pipefail

[ $# -lt 2 ] || {
    echo "Usage: $0 [basedir]" 1>&2
    exit 1
}

basedir=./outdir
[ $# -eq 1 ] && basedir="$1"

declare -A indirs

indirs=(
    [c]="$basedir"/cumulative
    [m]="$basedir"/monthly
)
outdir="$basedir"/png

. ~/.bash_aliases
shopt -s expand_aliases

. ~/python3_venv/bin/activate

Xvfb :101 -screen 0 2560x1440x24 1>/dev/null 2>&1 &
for type in m c
do
    indir=${indirs[$type]}
    time DISPLAY=:101 python3 src/mk_png.py $indir $outdir
done
killall Xvfb
