#! /bin/bash

[ $# -eq 3 ] || {
    echo Usage: $0 outdir sname 1>&2
    exit 1
}

outdir="$1"
sname="$2"

declare -A indirs

indirs=(
    [c]=./test/whole/cumulative
    [m]=./test/whole/monthly
)

outdir=./test/whole/png_ds9

. ~/python3_venv/bin/activate

# ds9 cannot be run in parallel
[[ $outdir =~ ds9 ]] && {

    . ~/.bash_aliases
    shopt -s expand_aliases

    ciao -o

    for type in c m
    do
	indir=${indirs[$type]}
	time python3 src/mk_png.py $indir $outdir --ds9
    done
    exit
}

mk_png_opts=

[[ $outdir =~ matplotlib ]] && { mk_png_opts='--matplotlib'; }
[[ $outdir =~ fitspng ]] && { mk_png_opts='--pngfits'; }

screen -dmS $sname bash -c 'exec bash'

for type in c m
do
    indir=${indirs[$type]}

    det=i
    for subdet in {0..0}
    do
	screen -S $sname -X screen bash -c "time python3 src/mk_png.py $mk_png_opts $indir $outdir -d $det -s $subdet -t $type; exec bash"
    done

    det=s
    for subdet in {0..2}
    do
	screen -S $sname -X screen bash -c "time python3 src/mk_png.py $mk_png_opts $indir $outdir -d $det -s $subdet -t $type; exec bash"
    done
done

screen -rS $sname
