#! /bin/bash

set -eo pipefail

SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

false && {
  echo 'This script recreates the HTML files.' >&2
  exit
}

[ $# -lt 2 ] || {
    echo "Usage: $0 [basedir]" >&2
    exit 1
}

basedir=/data/hrc/DoseMaps
[ $# -eq 1 ] && basedir="$1"

. ~/python3_venv/bin/activate

sdir="$basedir"/stats
pngdir="$basedir"/png
outdir="$basedir"/html
pdir="$basedir"/html/Plots

rm -rf $outdir
mkdir -p $outdir
cp -a "$SCRIPTDIR"/../html/Plots $outdir
ln -s "$pngdir" $outdir/Image
python3 "$SCRIPTDIR"/../src/mk_plots.py $sdir $pdir
python3 "$SCRIPTDIR"/../src/mk_html.py $sdir $pngdir $outdir

rsync -az --delete $outdir/ /data/wdocs/rpete/HRC_Dosage --exclude Image
rsync -a --delete $pngdir/ /data/wdocs/rpete/HRC_Dosage/Image --exclude bak
