#! /bin/bash

. ~/python3_venv/bin/activate

sdir=./test/whole/stats
pngdir=./test/whole/png_fitspng
outdir=./test/whole/html
pdir=./test/whole/html/Plots

rm -rf $outdir
mkdir -p $outdir
cp -a html/Plots $outdir
ln -s ../../../$pngdir $outdir/Image
python3 ./src/mk_plots.py $sdir $pdir
python3 ./src/mk_html.py $sdir $pngdir $outdir
